set_property IOSTANDARD LVCMOS33 [get_ports {rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[0]}]
set_property PACKAGE_PIN J19 [get_ports {rgb[2]}]
set_property PACKAGE_PIN G17 [get_ports {rgb[1]}]
set_property PACKAGE_PIN K18 [get_ports {rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property PACKAGE_PIN V17 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports {test[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[0]}]
set_property PACKAGE_PIN J2 [get_ports {test[2]}]
set_property PACKAGE_PIN L2 [get_ports {test[1]}]
set_property PACKAGE_PIN J1 [get_ports {test[0]}]

