set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rxd]
set_property IOSTANDARD LVCMOS33 [get_ports txd]
set_property PACKAGE_PIN B18 [get_ports rxd]
set_property PACKAGE_PIN A18 [get_ports txd]

set_property IOSTANDARD LVCMOS33 [get_ports {test[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test[0]}]
set_property PACKAGE_PIN V19 [get_ports {test[3]}]
set_property PACKAGE_PIN U19 [get_ports {test[2]}]
set_property PACKAGE_PIN E19 [get_ports {test[1]}]
set_property PACKAGE_PIN U16 [get_ports {test[0]}]
